-- SQLite (TASK 19)

SELECT CUSTOMERS.NAME AS Customer_Name, COUNT(LOCATIONS.ID) AS Rental_Count
FROM CUSTOMERS
JOIN LOCATIONS ON CUSTOMERS.ID = LOCATIONS.CUSTOMER_ID
GROUP BY CUSTOMERS.ID
HAVING COUNT(LOCATIONS.ID) >= 2;
