-- SQLite (TASK 18)

SELECT EMPLOYEES.NAME AS Employee_Name, COUNT(LOCATIONS.ID) AS Rental_Count
FROM EMPLOYEES
JOIN LOCATIONS ON EMPLOYEES.ID = LOCATIONS.EMPLOYEE_ID
GROUP BY EMPLOYEES.ID
HAVING COUNT(LOCATIONS.ID) >= 2;
