-- SQLite (TASK 20)

SELECT L.ID AS Rental_ID, C.NAME AS Customer_Name, CAR.NAME AS Car_Name, E.NAME AS Employee_Name
FROM LOCATIONS L
JOIN CUSTOMERS C ON L.CUSTOMER_ID = C.ID
JOIN CARS CAR ON L.CAR_ID = CAR.ID
JOIN EMPLOYEES E ON L.EMPLOYEE_ID = E.ID;

